ble: Add missing include for __weak definition
This fixes this compiler error for compilation setups that don't include the
HAL header file by default across all compilation units:

Middlewares/ST/STM32_WPAN/ble/svc/Src/svc_ctl.c:71:7: error: expected ';' before 'void'
   71 | __weak void DIS_Init( void )
      |       ^~~~~
      |       ;
Middlewares/ST/STM32_WPAN/ble/svc/Src/svc_ctl.c:75:7: error: expected ';' before 'void'
   75 | __weak void EDS_STM_Init( void )
      |       ^~~~~
      |       ;

...